
server.port=8080

# Database (PostgreSQL)
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:${postgresql://postgres:gHSvzYQTibQihOTFJVNBJbwRgQcGnvra@postgres.railway.internal:5432/railway}
#spring.datasource.username=postgres
#spring.datasource.password=gHSvzYQTibQihOTFJVNBJbwRgQcGnvra
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Jackson
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Logging
logging.level.com.example.TeamTaskManager=DEBUG
